# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct', models.BooleanField(verbose_name='Ответ верный')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name_plural': 'ответы',
                'verbose_name': 'ответ',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SIMPLE_CHOICE', 'простой выбор'), ('NUMERIC', 'числовой')], max_length=250, verbose_name='Тип теста')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('answers', models.TextField(verbose_name='JSON с ответами')),
            ],
            options={
                'verbose_name_plural': 'вопросы теста',
                'verbose_name': 'вопрос теста',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
            ],
            options={
                'verbose_name_plural': 'сеанс тестирования',
                'verbose_name': 'сеанс тестирования',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_limit', models.BooleanField(default=False, verbose_name='Ограничение по времени')),
                ('duration', models.PositiveIntegerField(verbose_name='Продолжительность(мин.)')),
                ('active', models.BooleanField(verbose_name='Тест активен')),
            ],
            options={
                'verbose_name_plural': 'тесты',
                'ordering': ['title'],
                'verbose_name': 'тест',
            },
        ),
        migrations.AddField(
            model_name='session',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Test', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Question', verbose_name='Тест'),
        ),
        migrations.AddField(
            model_name='answer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.Session', verbose_name='Сеанс'),
        ),
    ]
